### PR TITLE
Prepare for log base being a parameter

### PR DESCRIPTION
**Pull request by ahcm**
Hi,

what do you think about making the log base a parameter?

Cheers
Andy

### CODE REVIEW

**Comment by 38** [comment]
Yes, this is definitely useful :)  

Seems you haven't not exposed the base param. So I guess this is one part of the work right? Do you planning keep working on this?

Thanks for the PR
Hao

**Comment by ahcm** [comment]
Sorry, I overlooked your reply. Yes, if you are OK, with this I would continue two work on it.

**Comment by ahcm** [comment]
It might be, that you know better about exposing the param, since it tis your API.

**Comment by 38** [comment]
As log base is already added to master, closing this PR. Thanks!

**Pull request closed without merging**
