### PR TITLE
Add support for typestyles like "oblique" or "monospace"

### PR DESCRIPTION
**Pull request by TatriX**
Currently default hardcoded typeface is "Arial", but this font is not
available by default everywhere. This commit allows using typestyles
like "monospace" instead of concrete typefamily, thus using system
defaults.

### CODE REVIEW

**Comment by TatriX** [comment]
I've only tested this on Linux.

**Comment by 38** [comment]
Hi,
Thanks for the PR. I confirm it works with OSX as well. I really like the idea and think we definitely should have this. 

But I have a few more notes on that. As you may realized that, we actually use the `Font::name` which is the font-family name when we generate SVG images. 

However, the SVG spec doesn't support "oblique", "italic", "bold" in `font-family` field. 

Generally speaking, I think monospace seems a good description of font name, which refers the default monospace. And otherwise, it seems we could have a default font setting. 

For bold, italic and oblique, all those seems to be a variant of the same font. Thus I think it's better to make another API that allows user choose different variants. 

So to conclude my thoughts, I think it's a good idea in general. And could we only support "default" and "monospace". For other options, I think I should create another task to design a better  API for them.

Thanks again!
Hao

**Comment by 38** [comment]
I see, that's cool.  

You mean for the SVG, we can always put the actual font family name to the attribute? But for SVG it seems nice to have some generic font family name. So should it is compatible with SVG and CSS, thus our SVG backend can produce valid output.

**Comment by TatriX** [comment]
For some reason I used `oblique` without actually understanding what it means...
I've added a new type `FontFamily` which should make a bit more sense then previous approach.
Tomorrow I'll take a look at the changes I've made again, as it seems I'm too tired to think properly ;)

**Pull request closed without merging**
